# -*- coding: utf-8 -*-
"""26ai60r21_assignment3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RRAF42uVfzcg4abLuEnChh3WC6LCr2w0

# <font color='seablue'>**Assignment: Multinomial Naive Bayes**
### SMS Spam Classification
**Total Marks: 20**

### <font color = "orange"> Q1. Load the SMS Spam Collection dataset from: https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import string
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

df = pd.read_csv("sms.tsv.txt",sep="\t",names = ["label","message"])
print(df.info())

df.shape

"""### Check for and handle duplicate entries and missing values in the dataset. """

df.duplicated().sum()

df.drop_duplicates()

"""###Show the class distribution of the dataset and state whether the dataset is well balanced or not."""

X = df["message"]
y = df["label"]
sns.countplot(x="label", data=df)
plt.xlabel("Class")
plt.ylabel("Number of messages")
plt.title("SMS class distribution")
plt.show()

"""By seeing the countplot we can clearly see that number of ham labels are more than the spam , so based on this we can say that they are not well distributed...

###  Preprocess the message text (convert to lowercase and remove punctuation) so it's ready for vectorization. 
"""

s = df.shape
n = s[0]
for i in range(n):
    df.iloc[i,1] = (df.iloc[i,1]).lower()

for i in range(df.shape[0]):
    df.iloc[i, 1] = ''.join(
        char for char in df.iloc[i, 1]
        if char not in string.punctuation
    )
df

"""### Split the dataset into training and test sets (80%-20%)."""

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.20,random_state=42)

"""#####We split on the raw text **before** vectorizing, so that the vocabulary used in Q6 is built only from the training set — fitting the vectorizer on the full dataset (train + test) would leak test-set vocabulary into training, which is a subtle form of data leakage.

### Convert the preprocessed messages into count vectors (bag-of-words) using CountVectorizer, fitting only on the training data.
"""

vectorizer = CountVectorizer(stop_words="english")
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

"""##### A **bag-of-words** representation turns each message into a vector of word counts against a fixed vocabulary — e.g. the message `"free entry free"` becomes a vector where the column for `"free"` has value 2, `"entry"` has value 1, and every other vocabulary word is 0. This is exactly the kind of count data Multinomial Naive Bayes is built for. We cap the vocabulary size and drop common English stopwords to keep the feature space manageable and focused on informative words.

###Design a Multinomial Naive Bayes classifier from scratch and fit it on the training set. 

##### <font color='black'>**Idea:** Multinomial NB models each class $C$ as having its own word-usage distribution — feature $i$ (word $i$) occurs with probability $p_{C,i}$ within class $C$'s documents. For a document with word counts $x_1, \ldots, x_n$, the likelihood is:$$P(\mathbf{x} \mid C) \;\propto\; \prod_{i=1}^{n} p_{C,i}^{\,x_i}$$(The multinomial coefficient $\frac{(\sum_i x_i)!}{\prod_i x_i!}$ is dropped since it's the same for every class and doesn't affect which class has the highest posterior.) We estimate $p_{C,i}$ from training data with **Laplace (add-$\alpha$) smoothing**, so a word that never appeared in class $C$'s training documents doesn't get assigned zero probability:$$p_{C,i} = \frac{N_{C,i} + \alpha}{N_C + \alpha n}$$where $N_{C,i}$ is the total count of word $i$ across all class-$C$ documents, $N_C$ is the total word count across all class-$C$ documents, and $n$ is the vocabulary size. Combined with the class prior $P(C)$, we predict the class maximizing (in log-space, to avoid underflow):$$\log P(C \mid \mathbf{x}) \;\propto\; \log P(C) + \sum_{i=1}^{n} x_i \log p_{C,i}$$
"""

class MultinomialNB:
    def __init__(self, alpha=1.0):
        self.alpha = alpha

    def fit(self, X, y):
        self.classes = np.unique(y)
        n_classes = len(self.classes)
        n_features = X.shape[1]
        self.class_p = np.zeros(n_classes)
        self.feature_p = np.zeros((n_classes, n_features))
        for idx, c in enumerate(self.classes):
            X_c = X[y == c]
            self.class_p[idx] = np.log(X_c.shape[0] / X.shape[0])
            word_counts = np.asarray(X_c.sum(axis=0)).flatten()
            total_words = word_counts.sum()
            probabilities = (word_counts + self.alpha) / (total_words + self.alpha * n_features)
            self.feature_p[idx] = np.log(probabilities)
        return self

    def predict(self, X):
        predictions = []
        for row in X:
            scores = []
            for idx in range(len(self.classes)):
                score = self.class_p[idx]
                score += np.sum(row.toarray().flatten() * self.feature_p[idx])
                scores.append(score)
            predictions.append(self.classes[np.argmax(scores)])
        return np.array(predictions)

model = MultinomialNB(alpha=1.0)
model.fit(X_train_vec, y_train)
y_pred = model.predict(X_test_vec)

"""### Evaluate the test set using your custom Multinomial NB classifier and report accuracy, precision, recall, and confusion matrix."""

from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test,y_pred,pos_label="spam")
recall = recall_score(y_test,y_pred,pos_label="spam")
cm = confusion_matrix(y_test,y_pred,labels=["ham", "spam"])

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("Confusion Matrix:")
print(cm)

"""### Using scikit-learn's implementation of Multinomial NB, fit the training data and evaluate on the test set. How does the performance of this model compare with your custom implementation?"""

from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB(alpha=1.0)
nb.fit(X_train_vec, y_train)
y_sk = nb.predict(X_test_vec)
accuracy = accuracy_score(y_test, y_sk)
precision = precision_score(y_test,y_sk,pos_label="spam")
recall = recall_score(y_test,y_sk,pos_label="spam")
cm = confusion_matrix(y_test,y_sk,labels=["ham", "spam"])

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("Confusion Matrix:")
print(cm)

"""#### The custom implementation performs very similarly to the scikit-learn implementation .This indicates that the custom implementation correctly reproduces the main multinomial naive bayes calculations."""

